# Generated by Django 2.2.3 on 2019-07-11 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('harga', models.IntegerField(default=0)),
                ('provinsi', models.CharField(max_length=50)),
                ('kota', models.CharField(max_length=50)),
                ('kodepos', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(null=True)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('review', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('ratinghotel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel')),
            ],
        ),
    ]
